// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo5Q_Mcstag7OawMlayC1bSkZ9U-apj9I',
    appId: '1:647693282526:web:4ad53da42145906271e64f',
    messagingSenderId: '647693282526',
    projectId: 'firestorepractice-2294b',
    authDomain: 'firestorepractice-2294b.firebaseapp.com',
    storageBucket: 'firestorepractice-2294b.appspot.com',
    measurementId: 'G-L5TKJ7RDT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdhAHZ879Bo1sTSYOzi4P9UnVhITVsAS8',
    appId: '1:647693282526:android:cdbdabc11418285771e64f',
    messagingSenderId: '647693282526',
    projectId: 'firestorepractice-2294b',
    storageBucket: 'firestorepractice-2294b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyPX3GsGblnx8kDHtCpcsz8IAbuIlfPsU',
    appId: '1:647693282526:ios:6facd4d2d886890a71e64f',
    messagingSenderId: '647693282526',
    projectId: 'firestorepractice-2294b',
    storageBucket: 'firestorepractice-2294b.appspot.com',
    iosBundleId: 'com.example.firestorepracticle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyPX3GsGblnx8kDHtCpcsz8IAbuIlfPsU',
    appId: '1:647693282526:ios:ef23a63a4a7652c471e64f',
    messagingSenderId: '647693282526',
    projectId: 'firestorepractice-2294b',
    storageBucket: 'firestorepractice-2294b.appspot.com',
    iosBundleId: 'com.example.firestorepracticle.RunnerTests',
  );
}
